language: python
python: 3.5

install:
  - pip3 install pytest-cov pycodestyle codecov

script:
  - pip3 install -r requirements.txt
  - ./scripts/run-dev-mq.sh
  - ./scripts/run-task-queue.sh
  - pytest --cov=src
  - pycodestyle .

after_success:
  - codecov

services:
  - docker