broker: pyamqp://guest@localhost//
backend: rpc://
servers:
  montagu:
    url: http://localhost:8080
    user: test.user@example.com
    password: password
  orderlyweb:
    url: http://localhost:8888
tasks:
  diagnostic_reports:
    testGroup:
      testDisease:
        - report_name: minimal
        - report_name: other
          parameters:
            nmin: 0
