broker: pyamqp://guest@localhost//
backend: rpc://
servers:
  montagu:
    url: http://localhost:8080
    user: test.user@example.com
    password: password
  orderlyweb:
    url: http://localhost:8888
  smtp:
    host: localhost
    port: 25
    from: noreply@example.com
tasks:
  diagnostic_reports:
    poll_seconds: 5
    success_email:
      recipients:
        - modeller@example.com
        - science@example.com
      subject: "New version of Orderly report: {report_name}"
    reports:
      testGroup:
        testDisease:
          - report_name: minimal
          - report_name: other
            parameters:
              nmin: 0