broker: pyamqp://guest@localhost//
backend: rpc://
montagu_url: http://localhost:8080
montagu_user: test.user@example.com
montagu_password: password
orderlyweb_url: http://localhost:8888
diagnostic_reports:
  testGroup:
    testDisease:
      - report_name: minimal
      - report_name: other
        parameters:
          nmin: 0
