host: localhost
servers:
  montagu:
    url: http://localhost:8080
    user: test.user@example.com
    password: password
  orderlyweb:
    url: http://localhost:8888
  youtrack:
    token: None
  smtp:
    host: localhost
    port: 1025
    user:
    password:
    from: noreply@example.com
tasks:
  diagnostic_reports:
    use_additional_recipients: true
    poll_seconds: 5
    reports:
      testGroup:
        testDisease:
          - report_name: diagnostic
            success_email:
              recipients:
                - minimal_modeller@example.com
                - science@example.com
              subject: "VIMC diagnostic report: {touchstone} - {group} - {disease}"
            timeout: 300
            assignee: a.hill
          - report_name: diagnostic-param
            parameters:
              nmin: 0
            success_email:
              recipients:
                - other_modeller@example.com
                - science@example.com
              subject: "New version of another Orderly report"
            timeout: 1200
            assignee: e.russell
