host: localhost
servers:
  montagu:
    url: http://localhost:8080
    user: test.user@example.com
    password: password
  packit:
    url: https://localhost/packit
    disable_certificate_verify: true
  youtrack:
    token: None
  smtp:
    host: localhost
    port: 1025
    user:
    password:
    from: noreply@example.com
tasks:
  diagnostic_reports:
    use_additional_recipients: true
    poll_seconds: 5
    reports:
      testGroup:
        testDisease:
          - report_name: diagnostic
            success_email:
              recipients:
                - minimal_modeller@example.com
                - science@example.com
              subject: "VIMC diagnostic report: {touchstone} - {group} - {disease}"
            timeout: 300
            assignee: a.hill
            publish_roles:
              - minimal.modeller
              - Funders
          - report_name: diagnostic-param
            parameters:
              a: 1
              b: 2
              c: 3
            success_email:
              recipients:
                - other_modeller@example.com
                - science@example.com
              subject: "New version of another Orderly report"
            timeout: 1200
            assignee: e.russell
            publish_roles:
              - other.modeller
  archive_folder_contents:
    min_file_age_seconds: 0
