broker: pyamqp://guest@montagu_mq_1//
backend: rpc://
servers:
  montagu:
    url: http://montagu_api_1:8080
    user: test.user@example.com
    password: password
  orderlyweb:
    url: http://montagu_orderly_web:8888
  smtp:
    host: montagu_smtp_server_1
    port: 1025
    from: noreply@example.com
tasks:
  diagnostic_reports:
    use_additional_recipients: true
    poll_seconds: 5
    reports:
      testGroup:
        testDisease:
          - report_name: minimal
            success_email:
              recipients:
                - minimal_modeller@example.com
                - science@example.com
              subject:  "VIMC diagnostic report: {touchstone} - {group} - {disease}"
          - report_name: other
            parameters:
              nmin: 0
            success_email:
              recipients:
                - other_modeller@example.com
                - science@example.com
              subject: "New version of another Orderly report"
