broker: pyamqp://guest@montagu_mq_1//
backend: rpc://
servers:
  montagu:
    url: http://montagu_api_1:8080
    user: test.user@example.com
    password: password
  orderlyweb:
    url: http://montagu_orderly_web:8888
tasks:
  diagnostic_reports:
    poll_seconds: 5
    reports:
      testGroup:
        testDisease:
          - report_name: minimal
          - report_name: other
            parameters:
              nmin: 0
