name: test-and-push
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      YOUTRACK_TOKEN: ${{ secrets.YOUTRACK_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          pip3 install pytest-cov pycodestyle codecov
          pip3 install -r requirements.txt

      - name: Run dependencies
        run: ./scripts/run-dependencies.sh

      - name: Build docker
        run: ./scripts/build-docker.sh

      - name: Run docker worker
        run: ./scripts/run-docker-worker.sh

      - name: Run tests
        run: pytest --cov=src

      - name: Extra logging
        run: docker logs task-queue-worker

      - name: Lint
        run: pycodestyle .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Push docker
        env:
          VAULT_DOCKERHUB_USERNAME: ${{ secrets.VAULT_DOCKERHUB_USERNAME }}
          VAULT_DOCKERHUB_PASSWORD: ${{ secrets.VAULT_DOCKERHUB_PASSWORD }}
        run: |
          echo $VAULT_DOCKERHUB_PASSWORD | \
            docker login -u $VAULT_DOCKERHUB_USERNAME --password-stdin
          ./scripts/push-docker.sh